name: butterfly_classification
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  google_fonts: 6.2.1
  flutter_spinkit: 5.2.1
  flutter_secure_storage: ^9.2.2
  cached_network_image: 3.3.1
  camera: ^0.11.0+1
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  dio: ^5.5.0+1
  image_editor_plus: ^1.0.6
  permission_handler: 11.3.1
  intl: 0.19.0
  sliding_up_panel: 2.0.0+1
  url_launcher: ^6.3.0
  flutter_map: ^7.0.2
  latlong2: 0.9.1
  fl_chart: 0.68.0
  pull_to_refresh: 2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

