name: butterfly_classification
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  google_fonts: 6.2.1
  flutter_spinkit: 5.2.1
  flutter_secure_storage: 9.0.0
  cached_network_image: 3.3.1
  camera: 0.10.6
  geolocator: 11.0.0
  image_picker: 1.1.1
  dio: 5.4.3+1
  image_editor_plus: 1.0.5
  permission_handler: 11.3.1
  intl: 0.19.0
  sliding_up_panel: 2.0.0+1
  url_launcher: 6.2.6
  flutter_map: 6.1.0
  latlong2: 0.9.1
  fl_chart: 0.68.0
  pull_to_refresh: 2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

